AWSTemplateFormatVersion: "2010-09-09"
Mappings: 
  AccountsMap:
    "123456789012":
      environment: "production"
      suffix: ""
      key: "arn:aws:kms:eu-central-1:123456789012:key/1234abcd-12ab-34cd-56ef-1234567890ab"
    "987654321098":
      environment: "development"
      suffix: "-dev"
      key: "arn:aws:kms:eu-central-1:987654321098:key/0987dcba-09fe-87dc-65ba-ab0987654321"
Resources: 
  TestBucket: 
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Join [ "", ["testbucket12321", !FindInMap [AccountsMap, !Ref "AWS::AccountId", suffix]]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !FindInMap [AccountsMap, !Ref "AWS::AccountId", key]